### PR TITLE
Replace Travis with GitHub Actions pytest

### PR DESCRIPTION
**Pull request by basnijholt**
See this passing build: https://github.com/basnijholt/phidl/actions/runs/1953649867

The advantage is native integration with Github and that they are **_super fast_**.

### CODE REVIEW

**Comment by basnijholt** [comment]
I will add Python 3.8 and 3.9 in a follow-up PR. Currently, the hashes are different and therefore the tests are failing.

We should probably discuss whether supporting old (and deprecated) Python versions is worth it.

**Comment by amccaugh** [comment]
Yes, I think at this point deprecating Python 2.7 would be wise -- I think enough time has passed since its official deprecation that most packages / libraries have moved entirely to python 3

**Comment by basnijholt** [comment]
OK great! I'll do that in a follow up PR. This one reaches parity with the current CI pipeline.

**Comment by amccaugh** [comment]
So last naive question for you -- does the github action workflow replace travis-ci? I notice the `pre-commit run --all` task doesn't execute pytest.  If it can replace travis-ci entirely I wouldn't be opposed to that

**Comment by basnijholt** [comment]
This PR adds a different workflow (different from the one I add in #126) which runs pytest and the tutorial script.

pre-commit does only fast checks which don't run the actual phidl code, it only performs style changes and runs static code checkers.

**Pull request merged**
