### PR TITLE
Add pre-commit with code linters

### PR DESCRIPTION
**Pull request by basnijholt**
Hi @amccaugh,

I have spent a lot of time reading the source code and noticed a few unused imports, unused variables, somewhat inconsistent styling and thought to add some automatic linting tools to the repo.

These tools ensure a consistent code style and fix potential bugs by statically analyzing the code.

I also add a Github Actions Workflow that runs the pre-commit tests on every commit.

I have already solved many issues that flake8 brought up, however, there are many more:
```
phidl/device_layout.py:259:19: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/device_layout.py:866:20: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
phidl/device_layout.py:1532:37: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
setup.py:15:1: E402 module level import not at top of file
docs/conf.py:36:5: E265 block comment should start with '# '
phidl/phidl_tutorial_example.py:118:1: E265 block comment should start with '# '
phidl/phidl_tutorial_example.py:305:1: E402 module level import not at top of file
phidl/phidl_tutorial_example.py:713:1: E402 module level import not at top of file
phidl/phidl_tutorial_example.py:713:1: F811 redefinition of unused 'pu' from line 7
phidl/phidl_tutorial_example.py:1079:1: E402 module level import not at top of file
phidl/phidl_tutorial_example.py:1094:1: E402 module level import not at top of file
phidl/phidl_tutorial_example.py:1096:1: E402 module level import not at top of file
phidl/routing.py:1170:21: F841 local variable 'radiusEff' is assigned to but never used
phidl/routing.py:1180:17: F841 local variable 'r1' is assigned to but never used
phidl/routing.py:1800:9: F841 local variable 'r' is assigned to but never used
phidl/font.py:18:1: F841 local variable 'imp_err' is assigned to but never used
phidl/font.py:68:1: C901 '_get_glyph' is too complex (23)
phidl/geometry.py:2:1: E265 block comment should start with '# '
phidl/geometry.py:889:17: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/geometry.py:1482:5: F841 local variable 't1' is assigned to but never used
phidl/geometry.py:1489:9: F841 local variable 'r1' is assigned to but never used
phidl/geometry.py:1490:9: F841 local variable 'r2' is assigned to but never used
phidl/geometry.py:1583:9: F841 local variable 'r1' is assigned to but never used
phidl/geometry.py:1584:9: F841 local variable 'r2' is assigned to but never used
phidl/geometry.py:1633:9: F841 local variable 'rect' is assigned to but never used
phidl/geometry.py:1806:16: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
phidl/geometry.py:1867:18: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/geometry.py:2400:9: F841 local variable 'taper_poly1' is assigned to but never used
phidl/geometry.py:2401:9: F841 local variable 'taper_poly2' is assigned to but never used
phidl/geometry.py:2855:5: F841 local variable 'BetaLmin' is assigned to but never used
phidl/geometry.py:3609:21: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/geometry.py:3635:20: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/geometry.py:3644:24: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/geometry.py:3648:24: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/geometry.py:4162:9: F841 local variable 'deepbox' is assigned to but never used
phidl/geometry.py:4380:11: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/geometry.py:4383:15: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/geometry.py:4804:5: F841 local variable 'row' is assigned to but never used
phidl/geometry.py:4831:5: F841 local variable 'gnd1' is assigned to but never used
phidl/geometry.py:4833:5: F841 local variable 'nets' is assigned to but never used
phidl/geometry.py:5047:22: E712 comparison to True should be 'if cond is True:' or 'if cond:'
phidl/geometry.py:5055:22: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
phidl/geometry.py:5077:22: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
phidl/geometry.py:5104:18: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
phidl/geometry.py:5114:18: E712 comparison to True should be 'if cond is True:' or 'if cond:'
```

I am willing to fix those to but I would just like to first confirm whether these changes are welcome?

### CODE REVIEW

**Comment by amccaugh** [comment]
Hi @basnijholt, thank you for the idea and pull request -- these changes would be very welcome, and it would be useful to have a more uniform style in the code.  Can you briefly describe (or link a description) what it would entail in terms of workflow for pushing new commits?  For instance, is it just a flake8 analyzer that passes/fails (like pytest or travis-ci), or is it code-reformatter like [black](https://github.com/psf/black)? (I'm not terribly familiar with the github workflow actions)

**Comment by basnijholt** [comment]
Thank you for your response!

One would just have to do this once: `pre-commit install` and then the pre-commit filters will be applied every single time you are making a commit.

I will briefly describe the different filters:
- black: makes code style changes according to the defined black style (maintained by Python Software Foundation)
- flake8: performs static code and style checks, and will not make changes but will force you to fix the issues (unless a specifier is added to ignore the line or file)
- pyupgrade: makes automatic changes to the code style, e.g., removing unneeded brackets
- isort: sorts imports according to the rules specified in the PEP8 document

Because your response seems positive, I will continue to fix those remaining flake8 issues.

**Comment by basnijholt** [comment]
I have fixed all issues, you can see the Github Action passing in my fork: https://github.com/basnijholt/phidl/runs/5470116061?check_suite_focus=true.

It will automatically be added once this PR is merged.

**Comment by amccaugh** [comment]
This is looking good, I'm going to retarget it towards the `dev` branch -- shouldn't change anything, just a few extra small commits

**Comment by amccaugh** [comment]
I went through and fixed them already -- I kept most of the changes from the `dev` branch already since I don't want to accidentally throw away meaningful code changes that were in `dev`, and it appears almost all the other changes were just formatting ones (everything except the hash in one of the test cases).

Now a useful question in terms of workflow:  since I removed a handful of the changes introduced by `black`, what is the best way to re-correct them?  Do I just run `black` locally and commit the changes?

**Comment by basnijholt** [comment]
I just had fixed all the issues myself and then when pushing noticed you did the same 😄 

I have pushed some style fixes that were needed for the changes from the dev branch.

**Comment by basnijholt** [comment]
I don't understand why the Python 2.7 tests are failing. Otherwise everything succeeds.

Do you want me to investigate the Python 2.7 failure, or shall we just go ahead because Python 2.7 support will be dropped anyway?

**Comment by amccaugh** [comment]
It's a very strange error, but I suspect (since this has happened before) it's related to minor differences in floating point math causing tiny discrepancies -> creating rounding errors when converted to integers -> changes to the hash.  It usually happens because different system architectures perform floating point math ever-so-slightly differently.  I'd suspect that the backend github-actions is using is slightly different version of linux or underlying cpu architecture than travis-ci, and we're seeing the result of that.  I suggest we just ignore it and drop 2.7 support

**Comment by basnijholt** [comment]
OK great! Anything else I can do before merging in that case? 😄

**Comment by amccaugh** [comment]
I think we're all good!  Does it make the most sense in your opinion to merge this pre-commit PR first and then the travis-replacement PR second?  I don't see any issues with the ordering but I haven't worked with this process before

**Comment by basnijholt** [comment]
It shouldn't matter really they do not touch the same files :)

The order you suggest seems good!

**Comment by amccaugh** [comment]
Thanks again for the PR @basnijholt .  I have two more very basic questions if you have the time:

- Where do I go to check the status of a given build / see potential errors in pytest?
- Do you happen to know how to set up the workflow such that it shows a "build | passing" type-badge like I prevoiusly had for travis-ci?

**Pull request merged**
