### PR TITLE
Add full font support to text

### PR DESCRIPTION
**Pull request by spauka**
# Full Font Support

First off - thanks for a fantastic library. Really enjoy using it.

This pull request adds support for fonts to the text function - rather than requiring the use of DEPLOF. I use the py-freetype library in order to do font conversions. The does add an extra dependency - however at the moment it is not imported until we try to use it.

## Usage Examples
Rendering text using system fonts

```py3
from phidl import Device
from phidl import quickplot as qp
import phidl.geometry as pg

D = Device('test')
D.add_ref(pg.text("Using Arial", layer=2, face="Arial", justify="right"))
f2 = D.add_ref(pg.text("Or Helvetica", layer=1, face="Helvetica LT Pro", justify="right"))
f2.move(destination=(0,-10))
qp(D)
```
Gives:
image

Crucially it gives support for barcode fonts such as:
```py3
from phidl import Device
from phidl import quickplot as qp
import phidl.geometry as pg

D = Device('test')
D.add_ref(pg.text("*12345*", layer=2, face="Code128bWin.ttf"))
qp(D)
```
image

## Unicode Support

As an additional advantage - we get full Unicode support 👍 
```py3
from phidl import Device
from phidl import quickplot as qp
import phidl.geometry as pg

D = Device('test')
D.add_ref(pg.text("안녕하세요", layer=2, face="SourceHanMono-Regular.otf"))
d2 = D.add_ref(pg.text("こんにちは", layer=1, face="SourceHanMono-Regular.otf"))
d2.move(destination=(0, -10))
qp(D)
```
image

## TODO
 - [x] Fix layer support
 - [x] Write unit tests
 - [x] Update documentation

Please let me know if you would like any extra information.

### CODE REVIEW

**Comment by amccaugh** [comment]
Thanks for the PR, I like the idea of this and the examples look great.  Looks like you noticed the Layers are erroring out, not clear to me on initial glance why that is.  One request and one question:

- Can you target this PR to the `dev` branch and make sure "allow maintainers to make edits" is checked?
- What is purpose of the boolean "XOR" operation?  If at all possible we should avoid that, as it's very computationally expensive.

**Comment by spauka** [comment]
Thanks Adam, the failure on the layers was due to my not supporting putting text onto multiple layers in one call - this issue is now fixed.

WRT to the expensive boolean XOR, I'm not sure there's an easy way of removing this dependency. It comes from the way fonts are constructed from multiple polylines. This is clear if we place each polyline onto a single layer. For example an 8 gets:
image

Using either subtraction or addition fails for complex letters or shapes. Such as:
imageimage

Strictly speaking, this method is also an assumption as glyphs *should* be filled with the non-zero winding rule, although I don't see a simple method to implement this.

To mitigate this cost as much as possible, the generated polylines are cached in the get_glyph function.

I will continue to add documentation and tests and will comment once that's done. Allow edits should be checked.

Thanks

**Comment by spauka** [comment]
Hey @amccaugh,

I've added unit tests and documentation, and fixed python 2.7 compatibility. It should be ready for review when you have time 😄

**Comment by amccaugh** [comment]
Thanks @spauka -- I very much appreciate the thoroughness / test-writing (still behind those on the waveguide module!). I'll try to take a look at it this weekend or early next week at the latest.

**Comment by amccaugh** [comment]
All set I think. Shuffled a few things around but no major changes, but mostly it looks good! I'm going to merge and after a few more minor additions I'll push this the next release  this week.  Thanks for the contribution Sebastian!

**Comment by spauka** [comment]
Thanks for the quick review :D

**Pull request merged**
