### PR TITLE
Add flexible routing alternative based on pp.smooth

### PR DESCRIPTION
**Pull request by jolzgrafe**
# Flexible routing alternative

This pull request adds `routing.route_smooth()`, a flexible routing tool built on top of `pp.smooth()`

`pr.route_manhattan()` is great for routing waveguides, but it's hard to adjust/control the routes it creates, which can be a problem if you need to avoid other devices or routes in a dense layout. `pp.smooth` is also great for waveguides but requires you to figure out your waypoints manually every time, which can get old. `route_smooth()` tries to address these limitations. I've found it helpful for my layouts, so I thought I'd open this PR in case y'all find it useful.

## Route geometries
`route_smooth()` itself is mostly a wrapper for `pp.smooth()`, but it comes with routing geometry functions that help you create the waypoints for `pp.smooth()` to follow. There are 7 of these routing geometries: 
- straight lines for ports that point to each other, 
- L-shapes for orthogonal ports that can be connected with one turn, 
- U-shapes for parallel ports that face each other or the same direction, 
- J-shapes for orthogonal ports that can't be directly connected with one turn, 
- C-shapes for parallel ports that face away from each other, 
- V-shapes for ports at odd angles that face a common intersection point, and 
- Z-shapes for any ports at odd angles. 

The first five (straight, L, U, J, and C) are the basic geometries required for manhattan routing. V- and Z- shapes can be used when ports aren't necessarily parallel/orthogonal. These route geometries are parameterized based on relative distances from the ports, so they are easy to adjust as required. There's also a simple manual option to provide your own set of waypoints, useful for more complex routes. 

All the different geometries and names are definitely cumbersome, but it's nice to create custom routes that do exactly what you want in just one line of code. Here's an example illustrating the geometries:

```python
from matplotlib import pyplot as plt
import numpy as np
from phidl import Device
from phidl import quickplot as qp
from phidl.routing import route_smooth
from phidl import set_quickplot_options
set_quickplot_options(show_ports=True, show_subports=False)

D = Device()

#straight route
port1 = D.add_port(name='S1', midpoint=(-50, 0), width=4, orientation=90)
port2 = D.add_port(name='S2', midpoint=(-50, 50), width=4, orientation=270)
Route = D.add_ref(route_smooth(port1, port2, route_type='straight'))

#L route
port1 = D.add_port(name='L1', midpoint=(30,0), width=4, orientation=180)
port2 = D.add_port(name='L2', midpoint=(0, 50), width=4, orientation=270)
Route = D.add_ref(route_smooth(port1, port2, route_type='L'))

#U route
port1 = D.add_port(name='U1', midpoint=(50, 50), width=2, orientation=270)
port2 = D.add_port(name='U2', midpoint=(80,50), width=4, orientation=270)
D.add_ref(route_smooth(port1, port2, radius=10, route_type='U', length1=50))
port1 = D.add_port(name='U3', midpoint=(50, 80), width=4, orientation=10)
port2 = D.add_port(name='U4', midpoint=(80, 130), width=4, orientation=190)
D.add_ref(route_smooth(port1, port2, route_type='U', length1=20))

#J route
port1 = D.add_port(name='J1', midpoint=(100, 25), width=4, orientation=270)
port2 = D.add_port(name='J2', midpoint=(130, 50), width=4,  orientation=180)
D.add_ref(route_smooth(port1, port2, route_type='J', length1=25, length2=10))
port1 = D.add_port(name='J3', midpoint=(115, 105), width=5, orientation=270)
port2 = D.add_port(name='J4', midpoint=(131, 130), width=5,  orientation=180)
D.add_ref(route_smooth(port1, port2, route_type='J', length1=25, length2=30))

#C route
port1 = D.add_port(name='C1', midpoint=(180, 35), width=4, orientation=90)
port2 = D.add_port(name='C2', midpoint=(178, 15), width=4, orientation=270)
D.add_ref(route_smooth(port1, port2, route_type='C', length1=15, left1=30, length2=15))
port1 = D.add_port(name='C3', midpoint=(150, 105), width=4, orientation=90)
port2 = D.add_port(name='C4', midpoint=(180, 105), width=4, orientation=270)
D.add_ref(route_smooth(port1, port2, route_type='C', length1=25, left1=-15, length2=25))
port1 = D.add_port(name='C5', midpoint=(150, 170), width=4, orientation=0)
port2 = D.add_port(name='C6', midpoint=(165, 170), width=4, orientation=0)
D.add_ref(route_smooth(port1, port2, route_type='C', length1=10, left1=10, length2=10, radius=4))

#Z route
port1 = D.add_port(name='Z1', midpoint=(230,0), width=4, orientation=190)
port2 = D.add_port(name='Z2', midpoint=(200, 50), width=3, orientation=-10)
D.add_ref(route_smooth(port1, port2, route_type='Z', length1=30, length2=40))

#V route
port1 = D.add_port(name='V1', midpoint=(250,50), width=5, orientation=284)
port2 = D.add_port(name='V2', midpoint=(280, 50), width=5, orientation=270-14)
D.add_ref(route_smooth(port1, port2, route_type='V'))

#manual route
port1 = D.add_port(name='M1', midpoint=(300, 0), width=4, orientation=0)
port2 = D.add_port(name='M2', midpoint=(350, 50), width=4, orientation=180)
pts = []
yturns = np.linspace(port1.y, port2.y, 3)
for idx, yturn in enumerate(yturns):
    pts.append((port1.x, yturn))
    pts.append((port2.x, yturn))
D.add_ref(route_smooth(port1, port2, radius=5, route_type='manual', manual_points=pts))

qp(D)
plt.show()
```

image

## Automatic manhattan routing
There's also an option to use automatic manhattan routing, which figures out the required routing geometry. This is definitely redundant with `pr.route_manhattan()`, but it is built on `Path` tools which is sort of nice. I'm not sure how useful this is given `route_manhattan()` already exists, but it was relatively easy to add once the route geometries were made. Example:

```python
import numpy as np
from phidl import Device
from phidl import quickplot as qp # Rename "quickplot()" to the easier "qp()"
from matplotlib import pyplot as plt
from phidl.routing import route_smooth
from phidl import set_quickplot_options
set_quickplot_options(show_ports=False, show_subports=False)

D = Device() 
pitch = 50
Ndevs = 7
test_range = 40
xdevs = np.arange(Ndevs)*pitch
ydevs = np.arange(Ndevs)*pitch
xtest = np.linspace(-1*test_range, test_range, Ndevs)
ytest = np.linspace(-1*test_range, test_range, Ndevs)
for xidx, xdev in enumerate(xdevs):
	for yidx, ydev in enumerate(ydevs):
		devname = '{}{}'.format(xidx, yidx)
		port1 = D.add_port(name=devname+'1', midpoint=(xdev, ydev), width=4, orientation=0)
		port2 = D.add_port(name=devname+'2', midpoint=(xdev+xtest[xidx], ydev+ytest[yidx]), 
						   width=4,  orientation=0)
		try: # routing can fail if ports are too close in some cases
			D.add_ref(route_smooth(port1, port2, route_type='manhattan_auto'))
		except:
			pass
qp(D)
plt.show()
```
image

Anyway, let me know if you have any questions/comments about this!

### CODE REVIEW

**Comment by amccaugh** [comment]
This is a great contributions @jolzgrafe , thank you.  I think it would make sense to use this to (eventually) deprecate route_manhattan, as that code is pretty old/ad-hoc and doesn't have any of the benefits of the Path module at all.  Let me take a look through it in the next couple weeks, but from from first glance I'm very happy with the organization

**Comment by jolzgrafe** [comment]
Sounds good. I'm happy with any changes you want to make! The automatic routing currently has some edge cases that it fails on by not giving `pp.smooth` enough room for bends. It would probably be better if the automatic routing could be trusted to always produce an error-free route for valid ports . I don't think this will need big changes, so I'll try to work on making the automatic routing more bend-radius aware.

**Comment by amccaugh** [comment]
So I've looked through this and I'm pretty happy with the organization by and large. I did a little renaming of things but for the most part the code is very coherent.  Organizationally, I think the way we should approach this is the following:

- `pr.path_NAME()` (e.g. `pr.path_manhattan` previously `pr.route_waypoints_manhattan`) and related functions create paths between ports for routing purposes
- `pr.route_NAME()` (e.g. `pr.route_smooth`) are convenience functions that create polygons immediately

The typical usage then becomes 


```python
# Smooth path
P = pr.path_manhattan(port1, port2, radius)
P_smooth = pp.smooth(P, radius)
P_smooth.extrude(X)

# Angular path
P = pr.path_manhattan(port1, port2, radius)
P.extrude(X)
```

Also, I recently added some functionality to allow for non-smooth paths, so I think it would make sense to have both `pr.route_smooth()` like you've implemented (for people doing e.g. waveguides) and `pr.route_sharp()` (for e.g. doing electrical wiring), where they both have the same `route_type` options (manhattan, L, C, etc).  Something like this:

```python
pr.route_sharp(port1, port2, route_type='manhattan',
            width1 = None, width2 = None, layer = 0)
```

One last thought I had was it might be nice to have a non-`CrossSection` based extrusion.  As flexible as CrossSections are, they're kind of overkill in a lot of situations.  Would you find it useful if `Path`s had a simpler extrusion option like this:

```python
P = pr.path_manhattan(port1, port2, radius)
P.extrude_width(width = 5, layer = 0)
```

**Comment by jolzgrafe** [comment]
Hey Adam, looks great. I agree with all the changes you made.  I like the sharp routing idea more compact electrical routes. I went ahead and combined the `route_sharp` you proposed into `route_smooth` and renamed the function just `route` (commit e8a360f). I thought since most of the logic/usage is identical whether smooth or sharp, it sense as a parameter.  (btw your improvements for sharp paths are nice. I tried extruding sharp paths before and was confused about the width changing.)

I saw you started a routing tutorial. Let me know if I can help with that, or anything else you want to do here.

One minor comment: I noticed you deprecated `pr.route_basic()`, but I'm not sure this new path-based routing fully replaces it. The `path_type='straight'` basic route is a simple trapezoid shape that lines up with the ports. I've used it a lot. That exact shape is hard to replicate with `Path` based stuff because of the way the ports always end up orthogonal to the path. But I guess a Z-route comes pretty close, so maybe it's not a big deal.

Regarding your question about simpler, non-`CrossSection` extrusions, I think that would be great. I make a lot of very simple CrossSections, which gets repetitive. Maybe rather than having a new extrusion function, you could just allow `extrude()`'s `cross_section` argument to  be a number that defines the width? Like this:

```python
P.extrude(cross_section=5.0, layer=0)
```

I guess the downside of that approach is you would need to add a `layer` argument to `extrude`, which would be a little confusing when using a real `CrossSection` (i.e. what layer would take precedence?).

## Improved manhattan routing
I should have posted this earlier, but in commit beebb1e I improved the manhattan routing bend-radius awareness so now it seems to always return an error-free route for any bend radius. Here's an example demonstrating that:

```python
import numpy as np
from phidl import Device
from phidl import quickplot as qp
from matplotlib import pyplot as plt
from phidl.routing import route
from phidl import set_quickplot_options
set_quickplot_options(show_ports=False, show_subports=False, new_window=True)

pitch = 50
Ndevs = 11
test_range = 30
port2_orientations = (0, 90, 180, 270)
xdevs = np.arange(Ndevs)*pitch
ydevs = np.arange(Ndevs)*pitch
xtest = np.linspace(-1*test_range, test_range, Ndevs)
ytest = np.linspace(-1*test_range, test_range, Ndevs)
orientations = (0, 90, 180, 270)
for orientation in orientations:
    D = Device() 
    for xidx, xdev in enumerate(xdevs):
        for yidx, ydev in enumerate(ydevs):
            devname = '({}, {}),'.format(xidx, yidx)
            port1 = D.add_port(name=devname+'1', midpoint=(xdev, ydev), width=4, orientation=0)
            midpoint2 = (xdev+xtest[xidx], ydev+ytest[yidx])
            port2 = D.add_port(name=devname+'2', midpoint=midpoint2, width=3,  orientation=orientation)
            D.add_ref(route(port1, port2, route_type='manhattan', radius=None))	
    qp(D)
    plot_name = 'Orientation {} deg'.format(orientation)
    plt.title(plot_name)
plt.show()
``` 
Orientation 0 deg
Orientation 90 deg
Orientation 180 deg
Orientation 270 deg

**Comment by amccaugh** [comment]
For the simplified `extrude()` I was thinking the defaults would look like this: `extrude(cross_section, layer = None)`
- For a simplified extrusion with uniform width of 1.7, you do `extrude(1.7, layer = 0)`
- For a slightly more advanced one with a linearly tapered width of 1.7->3.5, you do `extrude( [1.7, 3.5] , layer = 0)`
- For anything more complicated, you use standard CrossSection `X` and do `extrude(X)` as usual
- If you tried to run `extrude(X, layer = 3)` it can throw an informational error

I think with respect to `route()`, I'd prefer to keep things separate (e.g. `route_smooth()` and `route_sharp()`).  There's a few reasons I was thinking of, let me know if you agree:
- The code is generally more readable if the function names are more explicit + single-purpose
- You don't end up with a bunch of unused parameters (e.g. `smooth_options` when doing sharp/angular routing) 
- But in particular, thinking ahead -- I think naming it `route()` might cause problems down the road if there's new routing styles we want to implement.  For instance, if for some reason there's a "sinusoidal routing" method, then the fact that `route()` exists and already contains sharp+smooth routing implies that the sinusoidal routing should probably end up in there too, so we end up with even more parameters

Re: the radius-aware turning, I saw that! It's fantastic, I actually started modifying your example to show in the tutorial documentation already

**Comment by jolzgrafe** [comment]
That all sounds reasonable to me. I separated out the sharp and smooth routing functions in 80dcfa4. 

I'll start working on expanding the tutorial, unless you'd rather do that.

**Comment by amccaugh** [comment]
To follow up about afe81e2 :  I think the idea is that within `route_sharp` and `route_smooth`, we allow people to ignore the concept of a `cross_section` entirely, so I think avoiding that nomenclature in the argument list makes sense.  Maybe we just rename the `cross_section` argument to `width`?

```python
def route_smooth(
        port1, 
        port2, 
        radius=5, 
        width=None,
        path_type='manhattan', 
        manual_path=None, 
        smooth_options={'corner_fun': pp.euler, 'use_eff': True}, 
        layer=0, 
        **kwargs
        )
```

Note I also reordered the arguments above so that `width` comes earlier -- you did a thorough enough job that I'd be willing to assume the vast majority of people will only ever use the `path_type='manhattan'` option, so when writing code quickly I'm guessing most people will do the following as shorthand: 

`pr.route_smooth(port1, port2, 5, 1.7, layer = 1)`

 If that assumption is correct, this is a little preferable to writing out `'manhattan'` in the arguments list every time:

`pr.route_smooth(port1, port2, 5, 'manhattan', 1.7, layer = 1)`

**Comment by jolzgrafe** [comment]
Ya, I probably should've discussed that with you. This was my logic for adding a full `CrossSection` parameter:
- Most times people will be happy with the default (linear taper between port widths), and won't need to touch the `cross_section` parameter. I.e. they can just do `pr.route_smooth(port1, port2, 5, layer=1)`.
- Sometimes a user might want a more complicated cross section, like a sine taper or a cross section with multiple layers of different widths/offsets (e.g. for multiple masks). In this case we can just let them provide whatever `CrossSection` they want, and it's helpful to signal that by naming the parameter something obvious like `cross_section`.
- Now that I think about it: if the user can provide any `CrossSection` to `route_smooth()`/`route_sharp()`, then I'm having a hard time thinking of a case where they would need to resort to using the `path_***` functions directly. We might be able to de-emphasize those functions in the tutorial, making it a little simpler? We can definitely still mention them since it helps to understand what the `route_***` functions are doing, but I don't think users need them.

But I'm happy to change it to your approach too.

**Comment by amccaugh** [comment]
I think that makes a lot of sense -- that way there's symmetry between 

`mypath.extrude(cross_section = 1.7, layer= 1)`

and

`pr.route_smooth(port1, port2, radius = 5, cross_section = 1.7, layer= 1)`

Now for a bit more philosophical question -- I actually dislike the keyword `cross_section`, it's too long and it's not totally obvious what it means to a new user.  Should we just replace both with

`mypath.extrude(width = 1.7, layer= 1)`

and

`pr.route_smooth(port1, port2, radius = 5, width = 1.7, layer= 1)`

Obviously changing keyword terms isn't ideal, but this is the first big change since the Path module was released so I'm not terribly hesitant about it yet

**Comment by amccaugh** [comment]
Regarding the tutorial, I think you're right to de-emphasize the `path_` functions.  But I think that can just take the form of presenting the `route_` functions _first_ in the tutorial, then having a discussion of the `path_` afterwards

**Comment by jolzgrafe** [comment]
Sounds good. I'll try to get the tutorial ready for you to look at soon.

Regarding the `cross_section`/`width` question:

Pros of `cross_section`
1.  clearly signals to user that they can use advanced `CrossSection` tool
2.  already in use 
3.  it's unique, so it won't be conflated with other uses of `width` (not a big deal given good docs and tutorial)

Pros of `width`
1.  less typing :)
2.  More obvious what it does for the simple/common constant-width case, and docs will make clear advanced usage.
3.  More elegant, feels more PHIDL-esque (purely aesthetic argument - not a big deal)

Personally I lean towards `width`, but if you're concerned about backwards-compatibility,  keeping `cross_section` would be fine too.

**Comment by amccaugh** [comment]
That all sounds pretty much in line with what I'm thinking.  I've gone ahead and changed the keyword to `width`, and added functionality for both `Path.extrude()` and `route_sharp()`/`route_smooth()` to use the other width options:

```
width : None, int, float, array-like[2], or CrossSection
    If None, the route linearly tapers between the widths the ports
    If set to a single number (e.g. `width=1.7`): makes a fixed-width route
    If set to a 2-element array (e.g. `width=[1.8,2.5]`): makes a route
        whose width varies linearly from width[0] to width[1]
    If set to a CrossSection: uses the CrossSection parameters for the route
```

I tested the `extrude()` code and I think it works well (and gives useful/informative errors if you mess up the `layer` specification) but I haven't tested  `route_sharp()`/`route_smooth()`  quite yet.  I'll get around to it in a bit, but let me know if you see anything messed up

**Comment by jolzgrafe** [comment]
I finished the tutorial and also added the new routing stuff to the geometry reference. I think it's ready for you to take a look when you have time. Here are a few notes on the changes I made:

### Quadrilateral routing

I added the `route_quad()` function to replace the common use case of `route_basic()` where you just want a direct connect between ports. It's the simplest possible route, so I thought it would be nice to have. That behavior is hard to replicate with `route_smooth()` and `route_sharp()` because of the way extruded paths have end faces that are orthogonal to the path. You can see an example in the tutorial. 

### `width` keyword changes

I like the `width` keyword changes. But the default layer logic here is kind of involved

1. Having `layer=None` be the default is kind of confusing. I think the way you had it, an error was thrown if the user didn't provide a `layer` when `width` wasn't a cross_section. That error is a little annoying when you're just testing something out and it also disallows the "`layer=None` means don't add it" feature you added recently. But, if we just remove that error message, that's also not great, because if you forget to put in a layer, then you don't see anything, but don't get any errors (so you have no idea what's going on).
2. But, using `layer=0` as default also isn't great because then if you do something simple like `P.extrude(width=cross_section)`, you get an error message because the layer is ambiguous.

For now, I changed the default to `layer=np.nan`, and set the default to `layer=0`  inside the function (similar to what you did recently in `Device.add_polygon`). I think this works fine, but maybe  could also see an argument for just not dealing with all this logic and allowing a `width=cross_section` argument to quietly override the `layer` argument.

### Path initialization

I saw you changed the `Path` constructor to allow the path to not start at the origin. Currently, if you provide the  `Path` with an array/list of points, the path will not be forced to origin, but if you provide it another `Path` to initialize off of, the result is a path that is forced to the origin. __Is that the intended behavior?__ This caused `route_smooth` and `route_sharp` to have different behavior depending on whether you provide an array or a path in `manual_path`. For now I just check for the type in the `route_` functions.

**Comment by amccaugh** [comment]
>For now, I changed the default to layer=np.nan, and set the default to layer=0 inside the function (similar to what you did recently in Device.add_polygon). I think this works fine, but maybe could also see an argument for just not dealing with all this logic and allowing a width=cross_section argument to quietly override the layer argument.

I like that solution, I don't think it particularly matters what the default argument is as long as the user sees the program [Do What I Mean](https://en.wikipedia.org/wiki/DWIM)

> Path initialization

Good catch, that's an oversight!  I was trying to get away from the "everything always starts at the origin" behavior because it doesn't make sense, especially when specifying starting points manually.  Logically we'd want that to apply to the Path constructor for both points *and* Paths passed to it, so I'll go ahead and fix that.

**Comment by amccaugh** [comment]
OK, hitting the home stretch --  I added another handy routing function (`pr.route_xy()`) that I've been using a lot recently, and cleaned up the tutorial a little bit.  I'm going to add a few tests and write a `Path.hash_geometry()` function to use them with, then we should be able to pull this in.  Great work @jolzgrafe

**Comment by amccaugh** [comment]
All set.  I'll plan pull the PR into `dev` tomorrow, let me know if there's anything else you think needs changing

**Comment by jolzgrafe** [comment]
Looks great! The `xxyx` is an elegant way to control the path. One suggestion: maybe we could make the `path_xy` an option in  `route_smooth` and `route_sharp`? That way you can use smooth bends if you want, and it matches with all the other path-based stuff. I can make the needed changes tonight if you think it's a good idea.

**Comment by amccaugh** [comment]
I'd prefer to leave it separate, because otherwise we need a `directions` argument in `route_smooth()` and `route_sharp()`, or it would have to be an "invisible" `kwarg` option.  Also, I was thinking about possibly adding one more argument to control the relative distances of each of the x/y compnents in `xyxx`, which would double the problem

**Pull request merged**
